#!/bin/bash

# Script to echo the current version number.
# THIS IS THE ONLY PLACE IN ALL THE EVOLVOTRON SOURCE A HARDWIRED VERSION NUMBER SHOULD APPEAR

# NB If you edit this, "make distclean" and then rebuild (./BUILD) as there is no dependency checking

echo "0.6.3"
